#!/usr/bin/env node

var file = process.argv[2];
var content = require('fs').readFileSync(file).toString();

var md = require('markdown-it')({
  html: true,
  linkify: true,
  typographer: true
}).use(require('markdown-it-highlightjs'));

console.log(md.render(content));
